from pygame.locals import *

key_map: dict[int, str] = {
	K_BACKSPACE: "Backspace",
	K_TAB: "Tab",
	K_CLEAR: "Clear",
	K_RETURN: "Return",
	K_PAUSE: "Pause",
	K_ESCAPE: "Escape",
	K_SPACE: "Space",
	K_EXCLAIM: "!",
	K_QUOTEDBL: '"',
	K_HASH: "#",
	K_DOLLAR: "$",
	K_AMPERSAND: "&",
	K_QUOTE: "'",
	K_LEFTPAREN: "(",
	K_RIGHTPAREN: ")",
	K_ASTERISK: "*",
	K_PLUS: "+",
	K_COMMA: ",",
	K_MINUS: "-",
	K_PERIOD: ".",
	K_SLASH: "/",
	K_0: "0",
	K_1: "1",
	K_2: "2",
	K_3: "3",
	K_4: "4",
	K_5: "5",
	K_6: "6",
	K_7: "7",
	K_8: "8",
	K_9: "9",
	K_COLON: ":",
	K_SEMICOLON: ";",
	K_LESS: "<",
	K_EQUALS: "=",
	K_GREATER: ">",
	K_QUESTION: "?",
	K_AT: "@",
	K_LEFTBRACKET: "[",
	K_BACKSLASH: "\\",
	K_RIGHTBRACKET: "]",
	K_CARET: "^",
	K_UNDERSCORE: "_",
	K_BACKQUOTE: "`",
	K_a: "A",
	K_b: "B",
	K_c: "C",
	K_d: "D",
	K_e: "E",
	K_f: "F",
	K_g: "G",
	K_h: "H",
	K_i: "I",
	K_j: "J",
	K_k: "K",
	K_l: "L",
	K_m: "M",
	K_n: "N",
	K_o: "O",
	K_p: "P",
	K_q: "Q",
	K_r: "R",
	K_s: "S",
	K_t: "T",
	K_u: "U",
	K_v: "V",
	K_w: "W",
	K_x: "X",
	K_y: "Y",
	K_z: "Z",
	K_DELETE: "Delete",
	K_KP0: "Keypad 0",
	K_KP1: "Keypad 1",
	K_KP2: "Keypad 2",
	K_KP3: "Keypad 3",
	K_KP4: "Keypad 4",
	K_KP5: "Keypad 5",
	K_KP6: "Keypad 6",
	K_KP7: "Keypad 7",
	K_KP8: "Keypad 8",
	K_KP9: "Keypad 9",
	K_KP_PERIOD: "Keypad .",
	K_KP_DIVIDE: "Keypad /",
	K_KP_MULTIPLY: "Keypad *",
	K_KP_MINUS: "Keypad -",
	K_KP_PLUS: "Keypad +",
	K_KP_ENTER: "Keypad Enter",
	K_KP_EQUALS: "Keypad =",
	K_UP: "Up Arrow",
	K_DOWN: "Down Arrow",
	K_RIGHT: "Right Arrow",
	K_LEFT: "Left Arrow",
	K_INSERT: "Insert",
	K_HOME: "Home",
	K_END: "End",
	K_PAGEUP: "Page Up",
	K_PAGEDOWN: "Page Down",
	K_F1: "F1",
	K_F2: "F2",
	K_F3: "F3",
	K_F4: "F4",
	K_F5: "F5",
	K_F6: "F6",
	K_F7: "F7",
	K_F8: "F8",
	K_F9: "F9",
	K_F10: "F10",
	K_F11: "F11",
	K_F12: "F12",
	K_F13: "F13",
	K_F14: "F14",
	K_F15: "F15",
	K_NUMLOCK: "Numlock",
	K_CAPSLOCK: "Capslock",
	K_SCROLLOCK: "Scrollock",
	K_RSHIFT: "Right Shift",
	K_LSHIFT: "Left Shift",
	K_RCTRL: "Right Control",
	K_LCTRL: "Left Control",
	K_RALT: "Right Alt",
	K_LALT: "Left Alt",
	K_RMETA: "Right Meta",
	K_LMETA: "Left Meta",
	K_LSUPER: "Left Windows Key",
	K_RSUPER: "Right Windows Key",
	K_MODE: "Mode Shift",
	K_HELP: "Help",
	K_PRINT: "Print Screen",
	K_SYSREQ: "Sysrq",
	K_BREAK: "Break",
	K_MENU: "Menu",
	K_POWER: "Power",
	K_EURO: "Euro",
	K_AC_BACK: "Android Back Button",
}